/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gomoku;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 * Ramka odpowiadająca za ustawienia gry.
 *
 * @author kayne
 */
public class UstawieniaFrame extends javax.swing.JFrame implements InterfejsUstawien {
    
    Ustawienia ustawienia;
    MainFrame rodzic;

    /**
     * Creates new form UstawieniaFrame.
     * @param ust referencja do klasy z ustawieniami gry
     * @param parent referencja do głównej ramki gry
     */
    UstawieniaFrame(Ustawienia ust, MainFrame parent) {
        ustawienia = ust;
        rodzic = parent;
        initComponents();
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        ustawKontrolki();
    }
    
    /**
     * Ustawia wszystkie pola i kontrolki na właściwe pozycje.
     */
    private void ustawKontrolki() {
        setSkreśleniePól();
        setOznaczeniePól();
        setKtoZaczyna();
    }

    /**
     * Ustawia checkbox odpowiadający za Skreślenie Pól na prawdziwy, jeśli tak
     * wskazują ustawienia.
     */
    @Override
    public void setSkreśleniePól() {
        if (ustawienia.isSkreśleniePól() == true) {
            SkreśleniePólCheckBox.setSelected(true);
        }
    }

    /**
     * Ustawia checkbox odpowiadający za Oznaczenie Pól na prawdziwy, jeśli tak
     * wskazują ustawienia.
     */
    @Override
    public void setOznaczeniePól() {
        if (ustawienia.isOznaczeniePól() == true) {
            OznaczeniePólCheckBox.setSelected(true);
        }
    }
    
    /**
     * Ustawia radio odpowiadające za ustalenie, kto zaczyna partię.
     */
    @Override
    public void setKtoZaczyna() {
        if (ustawienia.isGraczZaczyna() == true) {
            jRadioButton1.setSelected(true);
        } else {
            jRadioButton2.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        OznaczeniePólCheckBox = new javax.swing.JCheckBox();
        SkreśleniePólCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        kolorGraczaButton = new javax.swing.JButton();
        kolorKomputeraButton = new javax.swing.JButton();
        kolorPólButton = new javax.swing.JButton();
        kolorOznaczeniaPólButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ustawienia gry");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        jTabbedPane1.setToolTipText("");

        OznaczeniePólCheckBox.setText("Oznaczenie pól");
        OznaczeniePólCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                OznaczeniePólCheckBoxStateChanged(evt);
            }
        });
        OznaczeniePólCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OznaczeniePólCheckBoxActionPerformed(evt);
            }
        });

        SkreśleniePólCheckBox.setText("Skreślenie pól");
        SkreśleniePólCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkreśleniePólCheckBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("<html>Oznacza od góry i lewej strony pola kolejnymi<br /> literami alfabetu i cyframi arabskimi:");

        jLabel2.setText("Skreśla kombinację 5 pionków, które wygrały partię:");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(SkreśleniePólCheckBox)
                    .add(OznaczeniePólCheckBox))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(OznaczeniePólCheckBox))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(SkreśleniePólCheckBox))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ogólne", jPanel1);

        jRadioButton1.setText("Użytkownik");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Program");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Kto ma zacząć partię?");

        jLabel7.setText("Ta zmiana będzie widoczna po rozpoczęciu nowej partii.");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(jRadioButton1)
                    .add(jLabel7)
                    .add(jRadioButton2))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .add(18, 18, 18)
                .add(jRadioButton1)
                .add(18, 18, 18)
                .add(jRadioButton2)
                .add(18, 18, 18)
                .add(jLabel7)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Zaczyna", jPanel2);

        kolorGraczaButton.setText("Kolor użytkownika");
        kolorGraczaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolorGraczaButtonActionPerformed(evt);
            }
        });

        kolorKomputeraButton.setText("Kolor komputera");
        kolorKomputeraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolorKomputeraButtonActionPerformed(evt);
            }
        });

        kolorPólButton.setText("Kolor krawędzi pól");
        kolorPólButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolorPólButtonActionPerformed(evt);
            }
        });

        kolorOznaczeniaPólButton.setText("Kolor oznaczenia pól");
        kolorOznaczeniaPólButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolorOznaczeniaPólButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Kolory pionów:");

        jLabel6.setText("Kolory planszy:");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(jLabel6)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(kolorPólButton)
                            .add(kolorGraczaButton))
                        .add(18, 18, 18)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(kolorKomputeraButton)
                            .add(kolorOznaczeniaPólButton))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jLabel5)
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(kolorGraczaButton)
                    .add(kolorKomputeraButton))
                .add(18, 18, 18)
                .add(jLabel6)
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(kolorPólButton)
                    .add(kolorOznaczeniaPólButton))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kolory", jPanel3);

        jLabel4.setLabelFor(jTabbedPane1);
        jLabel4.setText("<html>Aby zmienić ustawienia, zaznacz odpowiednie pole.<br /><br />\nZmiana będzie automatycznie wprowadzana, więc masz podgląd na wszystko co zmienisz.");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 520, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 197, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(52, 52, 52)
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OznaczeniePólCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OznaczeniePólCheckBoxActionPerformed
        if (OznaczeniePólCheckBox.isSelected() == true) {
            ustawienia.setOznaczeniePól(true);
            rodzic.getPlansza().odświeżPlanszę();
        } else if (ustawienia.isOznaczeniePól() == true) {
            ustawienia.setOznaczeniePól(false);
            rodzic.getPlansza().odświeżPlanszę();
        }
    }//GEN-LAST:event_OznaczeniePólCheckBoxActionPerformed
    
    private void SkreśleniePólCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkreśleniePólCheckBoxActionPerformed
        if (SkreśleniePólCheckBox.isSelected() == true) {
            ustawienia.setSkreśleniePól(true);
            rodzic.getPlansza().odświeżPlanszę();
        } else if (ustawienia.isSkreśleniePól() == true) {
            ustawienia.setSkreśleniePól(false);
            rodzic.getPlansza().odświeżPlanszę();
        }
    }//GEN-LAST:event_SkreśleniePólCheckBoxActionPerformed
    
    private void OznaczeniePólCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_OznaczeniePólCheckBoxStateChanged
    }//GEN-LAST:event_OznaczeniePólCheckBoxStateChanged
    
    private void kolorGraczaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolorGraczaButtonActionPerformed
        ustawienia.setKolorGracza(JColorChooser.showDialog(null, "Wybierz kolor…", Color.black));
        rodzic.getPlansza().odświeżPlanszę();
    }//GEN-LAST:event_kolorGraczaButtonActionPerformed
    
    private void kolorKomputeraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolorKomputeraButtonActionPerformed
        ustawienia.setKolorKomputera(JColorChooser.showDialog(null, "Wybierz kolor…", Color.black));
        rodzic.getPlansza().odświeżPlanszę();
    }//GEN-LAST:event_kolorKomputeraButtonActionPerformed
    
    private void kolorPólButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolorPólButtonActionPerformed
        ustawienia.setKolorPól(JColorChooser.showDialog(null, "Wybierz kolor…", Color.black));
        rodzic.getPlansza().odświeżPlanszę();
    }//GEN-LAST:event_kolorPólButtonActionPerformed
    
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        ustawienia.setGraczZaczyna(false);
        JOptionPane.showMessageDialog(this, "Zmiana będzie widoczna od nowej gry.", "Zmieniono ustawienia", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        ustawienia.setGraczZaczyna(true);
        JOptionPane.showMessageDialog(this, "Zmiana będzie widoczna od nowej gry.", "Zmieniono ustawienia", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void kolorOznaczeniaPólButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolorOznaczeniaPólButtonActionPerformed
        ustawienia.setKolorOznaczeniaPól(JColorChooser.showDialog(null, "Wybierz kolor…", Color.black));
        rodzic.getPlansza().odświeżPlanszę();
    }//GEN-LAST:event_kolorOznaczeniaPólButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox OznaczeniePólCheckBox;
    private javax.swing.JCheckBox SkreśleniePólCheckBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton kolorGraczaButton;
    private javax.swing.JButton kolorKomputeraButton;
    private javax.swing.JButton kolorOznaczeniaPólButton;
    private javax.swing.JButton kolorPólButton;
    // End of variables declaration//GEN-END:variables
}
